networks:
  app_network:
services:
  postgres:
    image: ankane/pgvector
    container_name: postgres
    ports:
      - "5432:5432"
    # restart: always
    # shm_size: 128mb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bison
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    networks:
     - app_network
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - ./data/redis:/var/lib/redis/data
    networks:
      - app_network


  backend:
    build: ./backend

    container_name: backend
    environment:
      - CLIENT_ID=45647cf96c7049399c055eb3f941a064
      - CLIENT_SECRET=5d811093eae14dc1ac090bcd05a9fac8

    ports:
      - "8000:8000"

    networks:
      - app_network
    depends_on:
     - postgres
     - redis